### ISSUE TITLE
[Bug]: Window formatting contents incorrectly  

### ISSUE THREAD

**Issue by jpagliaccio** [meerk40t/meerk40t#2293]
### Summary Description

Window formatting contents (gadgets) incorrectly. For example the Navigation pop-out window contents are cropped no matter the window size. Many Gtk warnings are produced for width and size. The Navigation window produces the most Gtk warnings.   

### Additional Details

For example: 

![image](https://github.com/meerk40t/meerk40t/assets/7680161/205db47e-5a10-47f3-90cc-504975c4568b)

In my shell window there are many repeated Gtk width warnings (eg: Negative content width -9).

### Crash logs

```shell
-------------------------------------------------------
Clicking the Navigate Button (a subset of the output)
-------------------------------------------------------
(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.475: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.510: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.510: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.539: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.539: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.573: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.573: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.624: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.624: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.656: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 08:56:28.657: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)
---------------------------------
Clicking Simulate Window Button 
--------------------------------- 
(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:26.697: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:26.698: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:26.699: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:26.699: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.482: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.482: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.487: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.487: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.494: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.494: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.500: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.500: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.501: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.501: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.502: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.502: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.504: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.504: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.505: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.505: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.507: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.507: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.509: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.509: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.510: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.510: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.512: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.512: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.513: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.513: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.514: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.514: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.516: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.516: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.517: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.517: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.518: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.518: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.520: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.521: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.540: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.540: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.542: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.542: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.543: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.543: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.544: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.544: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.849: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.880: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.881: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.882: /lib64/libibus-1.0.so.5: undefined symbol: g_task_set_static_name

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.882: Loading IM context type 'ibus' failed

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.904: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.904: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.904: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.904: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.904: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.904: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.904: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.904: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.904: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.905: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.905: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.905: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.905: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.905: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.905: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.905: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -7

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.905: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.905: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.905: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.905: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.905: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.905: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.905: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.930: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.930: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.930: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.963: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.963: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.963: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.997: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:27.997: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:27.997: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.029: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.030: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.030: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.052: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.061: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.061: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.061: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.070: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.070: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.070: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.086: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.086: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.086: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.103: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.103: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.103: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.120: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.120: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.120: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.138: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.139: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.139: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.156: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.156: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.156: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.172: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:28.172: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:28.172: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.492: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.492: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.492: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.492: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.492: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.492: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.492: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.492: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.527: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.527: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.527: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.527: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.527: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.527: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.527: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.527: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.527: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.527: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.527: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.528: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.528: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.528: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.528: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.528: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.528: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.558: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.558: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.558: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.558: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.558: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.558: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.558: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.559: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.559: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.559: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.559: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.559: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.559: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.559: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.559: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.559: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.559: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.591: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.591: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.591: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.591: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.591: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.591: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.591: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.591: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.623: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.623: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.623: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.623: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.623: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.623: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.623: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.623: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.656: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.656: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.656: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.656: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.656: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.656: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.656: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.656: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.688: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.688: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.703: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node header, owner GtkNotebook)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.703: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.703: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: Negative content height -3 (allocation 1, extents 2x2) while allocating gadget (node checkbutton, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: for_size smaller than min-size (0 < 14) while measuring gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.703: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkCheckButton

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: Negative content height -2 (allocation 0, extents 1x1) while allocating gadget (node check, owner GtkCheckButton)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.703: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.703: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(MeerK40t-Linux-32:109753): Gtk-WARNING **: 09:05:29.703: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -25

(MeerK40t-Linux-32:109753): Gtk-CRITICAL **: 09:05:29.703: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

### MeerK40t Version

v0.9.3001

### MeerK40t Type

Executable

### Your Operating System

Linux

**Comment by tatarize** [comment]
That's pretty spammy but basically anytime you don't give a control enough room it starts to scream like that.

**Comment by jpirnay** [comment]
We will look into the cropping issue. The numerous GTK warnings unfortunately can't be suppressed nor avoided, gtk is infamous for it's attitude

**Comment by jpirnay** [comment]
The cropping has been addressed ie a wxpython issue circumvented

**Comment by jpagliaccio** [comment]
I am (finally) able to run meerk40t from the python git source using a conda environment (as opposed to the precompiled version). For version v0.9.3002 running on Fedora 38 with Python 3.9.18 the navigation window formatting is working nicely but I get this (missing icons). I ran from the meerk40t directly. 

![image](https://github.com/meerk40t/meerk40t/assets/7680161/b65d7743-4c43-410c-8ece-5feadadd8fb0)

**Comment by jpirnay** [comment]
(just installing Fedora 39 on my vbox) This is true everywhere or just in this very window?
Hint: open console, enter ``set debug_mode True`` and then ``quit``. Restart meerk40t. You should now have a ``Debug``-menu entries under the panes menu - open Icons. Pick one from the combobox - can you see them?

**Comment by jpirnay** [comment]
Hmm
![grafik](https://github.com/meerk40t/meerk40t/assets/2670784/56f8e2c0-9059-4923-8d47-de14bb254058)

![grafik](https://github.com/meerk40t/meerk40t/assets/2670784/18070cb8-3334-4ab0-bbf7-b064bbc96b75)

Latest main...

**Comment by jpagliaccio** [comment]
I did a git pull and am at version V0.9.3002 and debug is on. The Navigation icons are showing now. It was only the Navigation icons that were missing. Thanks for your help. FYI - I am still getting the warnings below ... 

At startup -------------------------

06:20:19: Debug: ClientToScreen cannot work when toplevel window is not shown
06:20:19: Debug: ClientToScreen cannot work when toplevel window is not shown
06:20:19: Debug: ClientToScreen cannot work when toplevel window is not shown
06:20:19: Debug: ClientToScreen cannot work when toplevel window is not shown

(meerk40t.py:1402909): Gtk-WARNING **: 06:20:19.899: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:20:20.019: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:20:20.019: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:20:20.044: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:20:21.827: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:20:21.827: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)


Clicking on Navigation -------------------------

(meerk40t.py:1402909): Gtk-WARNING **: 06:26:10.591: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:26:10.591: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:26:18.222: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(meerk40t.py:1402909): Gtk-WARNING **: 06:26:18.222: Negative content width -14 (allocation 20, extents 17x17) while allocating gadget (node button, owner GtkButton)

**Comment by jpirnay** [comment]
From what I could establish the simplest way (not necessarily the one that you may like / need) is to reroute those messages to ``/dev/null``:
```
python3 ./meerk40t.py 2>/dev/null
```
